# Generated by Django 2.2.1 on 2019-10-03 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20190923_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likeb',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
